contember/interface

packages/ui/src/styles/components/dialog.sass

broken by https://github.com/contember/admin/commit/d15bb10f4588e96c1ad2f8c6a7fe0a6444e5aee8

Dialog: fix animation

---

docker-compose.yaml

Update postgres healthcheck

---

packages/admin-sandbox/src/components/ContentField.tsx
packages/admin/src/components/bindingFacade/richText/blockEditor/BlockEditor.tsx
packages/admin/src/components/bindingFacade/richText/blockEditor/FieldBackedElement.ts

- drop deprecated render option, 
- add custom element support

field backed editor elements update

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/useDynamicSingleChoiceField.ts

Closes contember/private-issues#10

select field hide empty option

---

packages/ui/src/styles/components/menu.sass

Closes https://github.com/contember/private-issues/issues/23

Add margin transition to menu expanding item

---

packages/admin/src/components/bindingFacade/fields/SelectField/commonStyles.ts

+ Options
+ Menu
+ Values (single & multi)
Closes https://github.com/contember/private-issues/issues/26
Closes: https://github.com/contember/private-issues/issues/18

Update select styles

---

packages/admin/src/styles/parts/fileInput.sass
packages/ui/src/components/Box/Box.sass

Closes https://github.com/contember/private-issues/issues/41

Fix z-index & regresion padding

---

packages/ui/src/styles/components/editorCanvas.sass

Closes https://github.com/contember/private-issues/issues/15

Add padding to hovering toolbar

---

packages/ui/src/components/Layout/LayoutPage.sass

Fix sticky position on mobile/tablet

---

packages/admin/src/components/ApplicationEntrypoint.tsx

ApplicationEntrypoint: add default route for 'index' page

---

packages/admin/src/styles/_globalOverrides.sass
packages/admin/src/styles/index.sass
packages/ui/src/components/Layout/LayoutChrome.sass
packages/ui/src/components/Layout/LayoutPage.sass
packages/ui/src/components/Layout/LayoutPage.tsx
packages/ui/src/styles/components/titleBar.sass

- Fixes overflowing toolbar issues
- Fixes ignored bottom padding
- Fixes hovering toolbar not working sticky position
Closes https://github.com/contember/private-issues/issues/14
Closes https://github.com/contember/private-issues/issues/33

Use position sticky on all required layout panels

---

packages/ui/src/styles/_themeSchemes.css

Add `color-scheme` rules

---

packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx

Fix has erros condition

---

packages/admin-sandbox/src/pages/InputsPage.tsx
packages/admin/src/components/bindingFacade/fields/SlugField.tsx
packages/ui/src/components/Forms/Button/Button.sass
packages/ui/src/components/Forms/SlugControl/SlugInput.sass
packages/ui/src/components/Tabs/TabButton.sass
packages/ui/src/components/Typography/Label.sass
packages/ui/src/styles/abstract/controlVariants.sass
packages/ui/src/styles/abstract/implementsCustomFocusEffects.sass
packages/ui/src/styles/components/editorCanvas.sass
packages/ui/src/styles/components/menu.sass
packages/ui/src/styles/components/tag.sass

- sandbox: add two slug fields with different settings
- fix slug field
Closes #

Slug field fix

---

packages/ui/src/styles/components/hoveringToolbar.sass

Fix z-index of contextual hovering toolbar

---

packages/admin/src/styles/_globalOverrides.sass
packages/ui/src/styles/_customProperties.sass
packages/ui/src/styles/abstract/controlEssentials.sass
packages/ui/src/styles/components/select.sass

_Screenshot of Demo in Firefox 94.0.2_
Closes https://github.com/contember/private-issues/issues/48

Fix vertical alignment in Firefox

---

packages/admin/src/components/pageRouting/useEntityRedirectOnPersistSuccess.ts

The goal se to replace
~~~tsx
redirectOnSuccess={(request, id) => ({
...request,
pageName: "article",
parameters: {
id,
},
})}
~~~
with 
~~~tsx
redirectOnSuccess={(_, id) => ({ pageName: "article", parameters: { id } })}
~~~

RedirectOnSuccessHandler: allow IncompleteRequestState

---

packages/ui/src/styles/_variables.scss
packages/ui/src/styles/components/dropdown.sass

Remove unused SASS variables

---

packages/ui/src/components/SeamlessDropdown/SeamlessDropdown.sass
packages/ui/src/components/SeamlessDropdown/SeamlessDropdown.tsx
packages/ui/src/components/SeamlessDropdown/index.sass
packages/ui/src/components/SeamlessDropdown/index.ts
packages/ui/src/components/index.sass
packages/ui/src/styles/components/index.sass
packages/ui/src/styles/components/userMiniControl.sass

Closes https://github.com/contember/private-issues/issues/7

Update `SeamlessDropdown` styles & `UserMiniControl`

---

packages/ui/src/components/Layout/LayoutChrome.sass

Fix panels z-index on mobile

---

ee/admin-server/public/_panel/index.html
ee/admin-server/public/index.html
packages/admin-sandbox/src/index.html

Handle notch

---

packages/admin-i18n/src/messages/csCZ.ts
packages/admin-sandbox/api/migrations/2022-01-26-105400-add-blocks-repeater.json
packages/admin-sandbox/api/model/InputShowcase.ts
packages/admin-sandbox/src/pages/InputsPage.tsx
packages/admin/src/adminDictionary.ts
packages/admin/src/components/bindingFacade/collections/BlockRepeater/AddNewBlockButton.tsx
packages/admin/src/components/bindingFacade/collections/BlockRepeater/Dictionary.ts
packages/admin/src/components/bindingFacade/collections/BlockRepeater/index.ts

Closes https://github.com/contember/private-issues/issues/27

Pass `addButtonText` prop to `AddNewBlockButton`

---

packages/admin/src/components/bindingFacade/richText/blockEditor/BlockEditor.tsx

Closes https://github.com/contember/private-issues/issues/20

Add `placeholder` prop to `BlockEditor`

---

packages/ui/src/components/Layout/LayoutChrome.sass
packages/ui/src/components/Layout/LayoutPage.sass

Fix hovering toolbars & z-indexes

---

packages/ui/src/components/Divider/Divider.sass
packages/ui/src/components/Divider/Divider.tsx

Add `none` size for `Divider` component

---

packages/ui/src/components/Forms/Button/Button.sass
packages/ui/src/components/Forms/Checkbox/Checkbox.sass
packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass
packages/ui/src/styles/_customProperties.sass

Closes https://github.com/contember/private-issues/issues/64

Unify link & buttonn label sizes

---

packages/ui/src/components/RepeaterItemContainer/RepeaterItemContainer.sass

Remove double backgound change on focus/active

---

packages/ui/src/styles/components/editorBlock.sass
packages/ui/src/styles/components/titleBar.sass

Closes https://github.com/contember/private-issues/issues/70

Fix obscured title

---

packages/ui/src/components/Section/Section.sass
packages/ui/src/components/Section/Section.tsx

Section: Add support for actions in header

---

packages/ui/src/styles/components/icon.sass

Icon: Align icon in the middle of the line

---

packages/admin/src/components/bindingFacade/collections/helpers/EmptyMessage.tsx
packages/ui/src/components/Box/Box.sass
packages/ui/src/components/Box/Box.tsx
packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx

FieldContainer & Box: Unify layout props

---

ee/admin-server/package.json
pnpm-lock.yaml

includes fix for this issue https://github.com/redis/node-redis/issues/1734﻿

admin server: upgrade redis to fix crash

---

packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass

Temporary fix for Safari performance issue
Closes https://github.com/contember/private-issues/issues/93

Comment out problematic style

---

packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass

This reverts commit 23212cf5b0a8b90b5a8c12250c3c94c07363c39f.

Revert "Comment out problematic style"

---

packages/ui/src/components/Box/Box.sass
packages/ui/src/components/Layout/LayoutPage.sass
packages/ui/src/components/RepeaterItemContainer/RepeaterItemContainer.sass
packages/ui/src/styles/components/editorBlock.sass
packages/ui/src/styles/components/editorBlockBoundary.sass
packages/ui/src/styles/components/titleBar.sass

Fix z-index

---

packages/ui/package.json

Export CSS from UI package to allow standalone use
Cc: @jonasNobile

Export UI styles

---

packages/admin-sandbox/admin/index.tsx
packages/admin-sandbox/admin/wdyr.ts
packages/admin-sandbox/package.json
pnpm-lock.yaml

Why did you render logs why the component re-rendered.
Enabled by default in Sandbox.

Add WDYR to sandbox

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/264)

Add option to re-run install

---

packages/admin/src/components/bindingFacade/collections/Repeater/SortableRepeaterContainer.tsx
packages/ui/src/styles/components/editorBlock.sass

Closes #236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/265)

Resolve root element for sortable container

---

packages/ui/src/styles/components/table.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/269)

Remove table overflow

---

packages/admin-sandbox/admin/components/customLinks.tsx
packages/admin/src/tenant/components/apiKey/CreateApiKeyForm.tsx
packages/admin/src/tenant/components/member/EditIdentity.tsx
packages/admin/src/tenant/components/otp/ConfirmOtpForm.tsx
packages/admin/src/tenant/components/password/CreateResetPasswordRequestForm.tsx
packages/admin/src/tenant/components/password/FillResetPasswordTokenForm.tsx
packages/admin/src/tenant/components/password/ResetPasswordForm.tsx
packages/admin/src/tenant/components/person/InviteUser.tsx
packages/admin/src/tenant/components/person/Login.tsx
packages/admin/src/tenant/components/project/CreateProjectForm.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/276)

use distinction=primary instead of intent=primary

---

packages/ui/src/styles/_themeSchemes.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/273)

Update contrasts & Update primary color

---

packages/admin/src/components/bindingFacade/fields/ColorField.tsx

Closes #278 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/281)

Bind `ColorField` correctly

---

packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts
packages/ui/src/styles/components/hoveringToolbar.sass

Update toolbar position on resize & fix overflow clipping
Closes: https://github.com/contember/private-issues/issues/65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/267)

Fix hovering toolbars

---

packages/ui/src/components/Forms/Button/Button.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/272)

Fix button intent

---

packages/admin-sandbox/admin/components/ContentField.tsx
packages/admin-sandbox/api/migrations/2022-04-22-093758-image-align.json
packages/admin-sandbox/api/model/Content.ts
packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/287)

Remove min-width on nested `FieldContainer`

---

ee/admin-server/src/controllers/ProjectController.ts
ee/admin-server/src/services/S3Manager.ts
ee/admin-server/src/utils/readReadable.ts
packages/admin/src/components/ApplicationEntrypoint.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/277)

admin server: replace relative paths in index.html

---

packages/admin/src/components/bindingFacade/collections/DataGrid/base/DataGridColumnHiding.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/BooleanCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/HasManyAbsentCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/SelectCellFilter.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/TextCell.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/296)

Fix grid columns hide checkbox

---

packages/ui/src/components/Stack/Stack.sass
packages/ui/src/components/Stack/Stack.tsx
packages/ui/stories/src/Helpers/Block.tsx
packages/ui/stories/src/Stack.stories.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/291)

Apply Stack justify as expected

---

ee/admin-server/public/_panel/main.tsx
ee/admin-server/src/controllers/ProjectController.ts
packages/admin/src/components/Identity/IdentityProvider.tsx
packages/admin/src/components/Login/LoginEntrypoint.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/280)

login: backlink support

---

.github/workflows/ci.yaml
docker-compose.yaml
ee/admin-server/public/_panel/pages/projectList.tsx
packages/admin/package.json
packages/admin/src/components/Identity/IdentityProvider.tsx
packages/admin/src/tenant/queries/me.ts
pnpm-lock.yaml

requires engine 1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/282)

panel: show "New project" action only when allowed to do so

---

packages/admin/src/components/bindingFacade/renderers/FeedbackRenderer.tsx
packages/binding/src/accessorTree/MutationRequestResponse.ts
packages/binding/src/accessorTree/QueryRequestResponse.ts
packages/binding/src/accessorTree/RequestError.ts
packages/binding/src/core/DataBinding.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/312)

GraphQlClient: handle top level graphql errors

---

packages/ui/src/components/Forms/Button/Button.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/308)

Replace browser defined font family of `button` elements

---

packages/admin/src/components/bindingFacade/collections/DataGrid/cells/GenericTextCellFilter.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/311)

Fix `null`

---

ee/admin-server/src/controllers/ApiController.ts
ee/admin-server/src/services/ApiEndpointResolver.ts
ee/admin-server/src/services/ApiRequestSender.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/317)

admin server: method restriction

---

ee/admin-server/src/utils/forwared.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/318)

admin-server: fix proxy request detection

---

ee/admin-server/src/dic.ts
ee/admin-server/src/services/Router.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/319)

admin-server: extract router

---

packages/ui/src/components/Dialog/Dialog.tsx
packages/ui/src/components/Dialog/DialogSettings.ts

Closes: #283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/322)

WIP: Dialog: Add gap prop to control dialog appearance

---

packages/ui/src/components/Forms/Button/Button.sass
packages/ui/src/components/Forms/Button/Button.tsx

Closes: #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/324)

Disable navigation when `AnchorButton` is disabled

---

packages/admin/src/components/bindingFacade/richText/ContemberEditor/methods/permissivelyDeserializeNodes.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/316)

Editor deserialization: Handle numbers, strings in quotes etc.

---

packages/ui/src/components/Grid/Grid.tsx
packages/ui/src/components/SaveButton.tsx
packages/ui/stories/src/ActionableBox.stories.tsx
packages/ui/stories/src/Aether.stories.tsx
packages/ui/stories/src/Box.stories.tsx
packages/ui/stories/src/Breadcrumbs.stories.tsx
packages/ui/stories/src/Button.stories.tsx
packages/ui/stories/src/ButtonGroup.stories.tsx
packages/ui/stories/src/ButtonList.stories.tsx
packages/ui/stories/src/Checkbox.stories.tsx
packages/ui/stories/src/Collapsible.stories.tsx
packages/ui/stories/src/ContainerSpinner.stories.tsx
packages/ui/stories/src/Divider.stories.tsx
packages/ui/stories/src/FieldContainer.stories.tsx
packages/ui/stories/src/Grid.stories.tsx
packages/ui/stories/src/Logo.stories.tsx
packages/ui/stories/src/Menu.stories.tsx
packages/ui/stories/src/Radio.stories.tsx
packages/ui/stories/src/RepeaterItemContainer.stories.tsx
packages/ui/stories/src/SaveButton.stories.tsx
packages/ui/stories/src/Select.stories.tsx
packages/ui/stories/src/Spacer.stories.tsx
packages/ui/stories/src/Spinner.stories.tsx
packages/ui/stories/src/Stack.stories.tsx
packages/ui/stories/src/TabButton.stories.tsx
packages/ui/stories/src/TextAreaInput.stories.tsx
packages/ui/stories/src/TextInput.stories.tsx
packages/ui/stories/src/Theme.stories.tsx
packages/ui/stories/src/TitleBar.stories.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/326)

UI fixes and tidy Storybook

---

ee/admin-server/package.json
ee/admin-server/src/utils/forwared.ts
package.json
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/327)

admin server fix

---

packages/ui/src/styles/abstract/controlVariants.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/331)

Improve disabled input readability

---

packages/ui/.storybook/global.sass
packages/ui/src/styles/_customProperties.sass
packages/ui/src/styles/index.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/330)

Change font to Inter

---

packages/admin/src/components/bindingFacade/environment/SideDimensions.tsx

cherry picked from #321 
closes #303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/332)

admin: fix side dimensions

---

packages/admin/src/components/bindingFacade/collections/DataGrid/grid/DataGrid.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/335)

datagrid: fix initial filter to avoid two queries

---

packages/admin-sandbox/admin/components/Layout.tsx
packages/admin-sandbox/api/migrations/2022-05-23-090850-locale-dialect.json
packages/admin-sandbox/api/model/Locale.ts
packages/admin/src/components/bindingFacade/environment/DimensionsSwitcher/DimensionsSwitcher.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/334)

Fix dimension switcher dependencies

---

packages/admin/src/components/bindingFacade/richText/blockEditor/embed/handlers/SpotifyEmbedHandler.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/336)

Spotify handler: Fix paste handling

---

packages/ui/src/components/Menu/MenuItem.tsx
packages/ui/src/components/Menu/Types.ts
packages/ui/stories/src/Menu.stories.tsx

Replaces the warning sign.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/337)

Add missing title fallback

---

packages/admin/src/tenant/components/member/EditMembership.tsx
packages/admin/src/tenant/components/member/VariableSelector.tsx
packages/admin/src/tenant/queries/roles.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/342)

Fix membership edit form - better generic variable field and hide predefined variables

---

packages/ui/src/components/Forms/Inputs/FloatInput.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/343)

FloatInput: Allow negative numbers

---

packages/binding/src/helperComponents/If.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/353)

fix If component with callback condition

---

packages/admin/tests/playwright/admin/index.sass
packages/admin/tests/playwright/admin/index.tsx
packages/admin/tests/playwright/admin/vite.config.ts
packages/admin/tests/playwright/utils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/351)

improve playwright dev usability

---

ee/admin-server/Dockerfile
packages/binding/src/dao/TreeNodeEnvironmentFactory.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/356)

Minor fixes

---

packages/admin/src/components/bindingFacade/richText/baseEditor/createEditorWithEssentials.tsx
packages/admin/src/components/bindingFacade/richText/plugins/element/headings/HeadingElement.ts
packages/admin/src/components/bindingFacade/richText/plugins/element/headings/withHeadings.ts
packages/admin/tests/tsconfig.json
packages/admin/tests/vitest/editor/plugins/heading.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/355)

Editor heading improvements

---

build/api/admin.api.md
build/api/ui.api.md
packages/admin-sandbox/admin/components/ContentField.tsx
packages/admin/src/components/bindingFacade/richText/RichEditor.ts
packages/admin/src/components/bindingFacade/richText/baseEditor/CustomElementPlugin.ts
packages/admin/src/components/bindingFacade/richText/baseEditor/EditorWithEssentials.ts
packages/admin/src/components/bindingFacade/richText/baseEditor/createEditorWithEssentials.tsx
packages/admin/src/components/bindingFacade/richText/plugins/attributes/alignment/alignButton.ts
packages/admin/src/components/bindingFacade/richText/plugins/attributes/alignment/index.ts
packages/admin/src/components/bindingFacade/richText/plugins/attributes/index.ts
packages/admin/src/components/bindingFacade/richText/plugins/element/headings/HeadingElement.ts
packages/admin/src/components/bindingFacade/richText/plugins/element/headings/HeadingRenderer.tsx
packages/admin/src/components/bindingFacade/richText/plugins/element/paragraphs/ParagraphElement.ts
packages/admin/src/components/bindingFacade/richText/plugins/element/paragraphs/ParagraphRenderer.tsx
packages/admin/src/components/bindingFacade/richText/plugins/index.ts
packages/admin/src/components/bindingFacade/richText/toolbars/HoveringToolbarContents.tsx
packages/admin/src/components/bindingFacade/richText/toolbars/ToolbarButtonSpec.ts
packages/ui/src/components/editor/EditorHeading.tsx
packages/ui/src/components/editor/EditorParagraph.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/358)

Editor align

---

packages/ui/src/components/Card/Card.tsx

Add class name for `active` state to help target styling of active state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/371)

Update Card: Add `active` prop

---

packages/ui/src/components/Card/Card.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/374)

Revert duplicate

---

packages/admin-sandbox/admin/components/ContentField.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/367)

Improve Sandbox: Move SelectField to `alternate`

---

packages/ui/src/components/Forms/Select/SelectCreateNewWrapper.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/373)

Improve SelectCreate wrapper: Change proximity of select and button

---

packages/ui/src/components/Table/Table.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/364)

Fix Table: Add missing coma

---

build/api/ui.api.md
packages/ui/src/components/Typography/Description.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/369)

Update Description: Add `className` prop

---

build/api/admin.api.md
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterFieldContainer.tsx
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterInner.tsx
packages/admin/src/components/bindingFacade/upload/internalComponents/BareFileRepeaterContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/368)

Fix RepeaterFieldContainer: Deprecate `boxLabel`, use label instead

---

build/api/admin.api.md
packages/admin/src/components/bindingFacade/upload/fileHandler/DiscriminatedFileHandler.tsx
packages/admin/src/components/bindingFacade/upload/fileHandler/SingleKindFileHandler.tsx
packages/admin/src/components/bindingFacade/upload/fileHandler/useFileHandler.ts
packages/admin/src/components/bindingFacade/upload/fileHandler/utils/staticRenderFileKind.tsx
packages/admin/src/components/bindingFacade/upload/fileKinds/FullFileKind.ts
packages/admin/src/components/bindingFacade/upload/fileKinds/factories/getStockAnyFileKind.tsx
packages/admin/src/components/bindingFacade/upload/fileKinds/factories/getStockAudioFileKind.tsx
packages/admin/src/components/bindingFacade/upload/fileKinds/factories/getStockImageFileKind.tsx
packages/admin/src/components/bindingFacade/upload/fileKinds/factories/getStockVideoFileKind.tsx
packages/admin/src/components/bindingFacade/upload/internalComponents/SingleFilePreview/SingleFilePreview.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/357)

upload field: allow children to be outside of baseEntity

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/hooks/useSelectOptions.ts

this allows implementation of dependent selects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/359)

select field: call custom createFilter even if query is empty

---

build/api/ui.api.md
package.json
packages/admin/src/components/bindingFacade/environment/DimensionsSwitcher/DimensionsRenderer.tsx
packages/ui/src/components/Forms/hooks/useNativeInput.ts
packages/ui/tests/cases/useNativeInput.test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/380)

Fix console warnings

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/hooks/useSelectOptions.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/384)

select: fix tree root id

---

build/api/admin.api.md
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/TextCell.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/385)

text cell: value is always string

---

packages/admin/src/components/bindingFacade/auxiliary/SimpleRelativeSingleField/SimpleRelativeFieldProxy.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/387)

Fix passing required flag

---

packages/admin/src/components/bindingFacade/renderers/FeedbackRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/390)

Don't use useRedirect in feedback renderer

---

packages/admin/src/components/bindingFacade/fields/useFieldControl.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/392)

fields: fix readOnly and disabled props passing

---

packages/binding/src/core/StateInitializer.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/391)

state initializer: initialize has-many relations from copy-from

---

packages/admin-sandbox/admin/components/Navigation.tsx
packages/admin-sandbox/admin/pages/nested/path.tsx
packages/ui/src/components/Section/Section.sass

https://user-images.githubusercontent.com/387611/183847436-d185e8d9-fb29-4c40-bb99-1c159298a20e.mov
https://user-images.githubusercontent.com/387611/183847469-27058966-da79-4d1c-a769-b0f1a422371c.mov
Closes https://github.com/contember/private-issues/issues/115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/398)

Fix scroll to position, use content top offset

---

packages/ui/src/components/Toaster/Toaster.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/401)

Fix padding causing covering of content below

---

build/api/admin.api.md
build/api/binding.api.md
packages/admin/src/components/ApplicationEntrypoint.tsx
packages/admin/src/components/Identity/HasRole.tsx
packages/admin/src/components/Identity/IdentityEnvironmentExtension.ts
packages/admin/src/components/Identity/IdentityProvider.tsx
packages/admin/src/components/Identity/index.ts
packages/admin/src/components/Project/ProjectEnvironmentExtension.tsx
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterInner.tsx
packages/admin/src/components/bindingFacade/richText/blockEditor/BlockEditor.tsx
packages/admin/src/components/bindingFacade/upload/internalComponents/selection/SelectFileInput.tsx
packages/admin/src/components/bindingFacade/upload/internalComponents/selection/SingleKindSelectFileDialog.tsx
packages/admin/src/tenant/components/otp/ConfirmOtpForm.tsx
packages/admin/src/tenant/components/otp/PrepareOtpForm.tsx
packages/admin/src/tenant/components/password/ChangePassword.tsx
packages/admin/src/tenant/components/password/CreateResetPasswordRequestForm.tsx
packages/admin/src/tenant/components/password/FillResetPasswordTokenForm.tsx
packages/admin/src/tenant/components/password/ResetPasswordForm.tsx
packages/admin/src/tenant/components/person/InviteUser.tsx
packages/admin/src/tenant/lib/useForm.ts
packages/admin/src/typings/react-fix.d.ts
packages/binding/src/accessorPropagation/EnvironmentContext.ts
packages/binding/src/accessorPropagation/EnvironmentContext.tsx
packages/binding/src/dao/Environment.ts
packages/binding/src/helperComponents/DeferredSubTrees.tsx
packages/binding/src/typings/react-fix.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/388)

extensible environment, add HasRole component

---

packages/admin/src/routing/RoutingLink.tsx

Closes https://github.com/contember/private-issues/issues/126
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/396)

RoutingLink: support target prop

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/DynamicMultiChoiceField.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/403)

multi choice field: fix anyMutation

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/hooks/useCreateOptionsFilter.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/407)

fix lazy select with zero init limit

---

build/api/binding.api.md
packages/binding/src/accessorTree/MutationRequestResponse.ts
packages/binding/src/core/DataBinding.ts
packages/client/src/crudQueryBuilder/CrudQueryBuilder.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/412)

fetch errorMessage on transaction field

---

build/api/binding.api.md
packages/binding/src/accessors/EntityAccessor.ts
packages/binding/src/accessors/EntityListAccessor.ts
packages/binding/src/accessors/FieldAccessor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/413)

entity accessor: add getParent and getMarker methods

---

packages/admin/src/components/bindingFacade/fields/ChoiceField/hooks/useOnAddNew.tsx
packages/admin/src/components/bindingFacade/fields/ChoiceField/renderDynamicChoiceFieldStatic.tsx
packages/binding/src/coreComponents/EntityListSubTree.tsx
packages/binding/src/dao/TreeNodeEnvironmentFactory.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/414)

remove usage of NIL_UUID

---

packages/ui/src/components/Layout/LayoutChrome.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/421)

Remove `console.log(barContentOffsetTop)`

---

packages/admin/src/components/bindingFacade/renderers/LayoutRenderer.tsx
packages/admin/src/components/bindingFacade/renderers/pageRenderers/DataGridPageRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/422)

Data grid page: allow after title

---

build/createViteConfig.js
ee/admin-server/package.json
ee/admin-server/public/_panel/main.tsx
ee/admin-server/vite.config.js
package.json
packages/admin-sandbox/admin/index.tsx
packages/admin-sandbox/vite.config.ts
packages/admin/src/components/pageRouting/Pages.tsx
packages/admin/tests/playwright/admin/index.tsx
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/424)

upgrade to vite 3

---

ee/admin-server/public/_panel/index.sass
ee/admin-server/vite.config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/427)

Server fix

---

packages/ui/src/styles/components/containerSpinner.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/426)

Fix containerSpinner CSS property

---

ee/admin-server/src/dic.ts
ee/admin-server/src/services/Router.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/430)

server: fix request timeout error handling

---

build/api/admin.api.md
build/api/binding.api.md
packages/admin/src/components/pageRouting/pageComponents/EditPage.tsx
packages/binding/src/accessorTree/AccessorTreeStateOptions.ts
packages/binding/src/accessorTree/PersistResult.ts
packages/binding/src/accessorTree/useDataBinding.ts
packages/binding/src/accessors/BindingConfig.ts
packages/binding/src/accessors/PersistErrorOptions.ts
packages/binding/src/core/Config.ts
packages/binding/src/core/DataBinding.ts
packages/binding/src/core/TreeAugmenter.ts
packages/binding/src/coreComponents/DataBindingProvider.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/417)

allow to skip state update after persist

---

packages/admin/src/components/bindingFacade/renderers/pageRenderers/DataGridPageRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/431)

Fix stretch layout

---

packages/admin/tests/playwright/cases/blockEditor.tsx
packages/admin/tests/playwright/cases/errorHandling.tsx
packages/admin/tests/playwright/cases/fieldContainer.tsx
packages/admin/tests/playwright/cases/fileSelection.tsx
packages/admin/tests/playwright/cases/layout.tsx
packages/admin/tests/playwright/cases/layoutWithTitleBar.tsx
packages/admin/tests/playwright/cases/lazySelect.tsx
packages/admin/tests/playwright/cases/radioInput.tsx
packages/admin/tests/playwright/cases/repeaterItemContainer.tsx
packages/admin/tests/playwright/cases/repeaterItemContainerWithActions.tsx
packages/admin/tests/playwright/cases/selectOrCreate.tsx
packages/admin/tests/playwright/cases/textInput.tsx
packages/ui/src/components/Layout/LayoutChrome.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/433)

Set initial scheme to `light`

---

packages/admin-i18n/src/messages/csCZ.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/432)

Fix: typo in csCZ messages

---

build/api/admin.api.md
packages/admin-sandbox/admin/pages/tags.tsx
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterFieldContainer.tsx
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterInner.tsx
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterItem.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/436)

repeater: support adding items to particular index

---

packages/binding/src/core/MutationGenerator.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/441)

fix deletes across multiple tree roots

---

packages/ui/src/components/Forms/Button/Button.tsx

Closes #443
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/444)

Disable `onClick` when disabled

---

packages/binding/src/core/MarkerMerger.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/440)

MarkerMerger: fix merging defaultValue

---

packages/binding/src/core/DataBinding.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/449)

DataBinding: stop processing when requests fails

---

packages/admin/src/components/bindingFacade/renderers/LayoutRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/451)

add navigation to static render of LayoutRenderer

---

build/api/admin.api.md
packages/admin-i18n/src/messages/csCZ.ts
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/BooleanCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/CoalesceTextCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/DateCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/EnumCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/GenericTextCellFilter.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/HasManySelectCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/HasOneSelectCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/NullConditionFilter.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/NumberCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/SelectCellFilter.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/TextCell.tsx
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/dataGridCellsDictionary.ts
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/442)

datagrid cells improvements

---

packages/ui/src/components/Forms/Inputs/TextareaInput.sass

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/455)

Allow textarea to grow

---

build/api/client.api.md
packages/client/src/content/upload/S3FileUploader.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/461)

s3: allow to override uploaded file content type

---

packages/admin/src/components/bindingFacade/upload/internalComponents/hooks/useNormalizedUploadState.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/463)

Fix order of uploaded files

---

build/api/admin.api.md
packages/admin-i18n/src/messages/csCZ.ts
packages/admin/src/adminDictionary.ts
packages/admin/src/components/Application/OutdatedApplicationChecker.tsx
packages/admin/src/components/Application/outdatedApplicationDictionary.ts
packages/admin/src/components/ApplicationEntrypoint.tsx
packages/admin/src/components/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/462)

add "outdated application dialog"

---

.github/workflows/ci.yaml
build/api/client.api.md
docker-compose.yaml
ee/admin-server/package.json
ee/admin-server/public/_panel/pages/studioGrid.tsx
packages/admin-sandbox/api/index.ts
packages/admin-sandbox/package.json
packages/admin/package.json
packages/admin/src/components/bindingFacade/collections/DataGrid/cells/CoalesceTextCell.tsx
packages/admin/tests/playwright/admin/index.tsx
packages/admin/tests/playwright/utils.ts
packages/binding/src/core/TreeParameterMerger.ts
packages/binding/src/queryLanguage/Parser.ts
packages/client/package.json
packages/client/src/content/params/whereToFilter.ts
packages/client/src/index.ts
pnpm-lock.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/467)

update @contember deps from engine

---

build/api/admin.api.md
packages/admin/src/components/bindingFacade/fields/HiddenField.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/477)

hidden field: do not require label

---

build/api/binding.api.md
packages/admin/src/components/bindingFacade/collections/Repeater/RepeaterInner.tsx
packages/admin/src/components/bindingFacade/upload/internalComponents/hooks/useNormalizedUploadState.ts
packages/binding/src/accessorSorting/SortedEntities.ts
packages/binding/src/accessorSorting/errors.ts
packages/binding/src/accessorSorting/useSortedEntities.ts

Entity list accessor must be refreshed when adding more entities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/478)

useSortedEntities: fix adding new entity

---

build/api/client.api.md
packages/admin-sandbox/admin/pages/index.tsx
packages/admin-sandbox/api/index.ts
packages/admin-sandbox/api/migrations/2022-11-24-135530-s3-max-size.json
packages/client/src/content/upload/GenerateUploadUrlMutationBuilder.ts
packages/client/src/content/upload/S3FileUploader.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/448)

S3: support new engine options

---

packages/vite-plugin/src/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/493)

fix(vite-plugin): rename meta attr "value" to "content"

---

ee/admin-server/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/505)

Add utilities package in docker

---

ee/cms-layout/package.json
packages/admin-i18n/package.json
packages/admin/package.json
packages/admin/src/components/pageRouting/Pages.tsx
packages/admin/src/components/pageRouting/Scopes/CreateScope.tsx
packages/admin/src/components/pageRouting/Scopes/DetailScope.tsx
packages/admin/src/components/pageRouting/Scopes/EditScope.tsx
packages/admin/src/components/pageRouting/Scopes/ListScope.tsx
packages/admin/src/components/pageRouting/Scopes/MultiEditScope.tsx
packages/binding/package.json
packages/client/package.json
packages/interface-tester/package.json
packages/react-client/package.json
packages/react-multipass-rendering/package.json
packages/react-utils/package.json
packages/ui/package.json
packages/vimeo-file-uploader/package.json
packages/vite-plugin/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/506)

Random fixes

---

ee/cms-layout/src/Root.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/513)

fix(cms-layout): Show close buttons in empty sidebars

---

ee/admin-server/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/517)

fix(admin-server): Fix start script

---

ee/cms-layout/src/Root.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/518)

fix(cms-layout): Fix hidden toggle when keep visible

---

packages/brand/src/2023/LogoIcon.tsx
packages/brand/src/2023/LogoType.tsx
packages/brand/src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/519)

fix(brand): Remove unsupported attr() fallback value

---

packages/admin-sandbox/admin/pages/article.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/522)

feat(admin-sandbox): Add back link to article edit

---

build/api/admin.api.md
packages/admin/src/components/pageRouting/Scopes/DataGridScope.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/523)

fix(admin): Remove render from `DataGridScope`

---

build/api/cms-layout.api.md
build/api/layout.api.md
packages/admin-sandbox/admin/components/AlertLogoutLink.tsx
packages/admin-sandbox/admin/components/Layout.tsx
packages/admin-sandbox/admin/components/Layouts/Layout.bare.tsx
packages/admin-sandbox/admin/components/Layouts/Layout.cms.tsx
packages/admin-sandbox/admin/components/Layouts/Layout.default.tsx
packages/admin-sandbox/admin/components/Layouts/index.ts
packages/admin-sandbox/package.json
packages/cms-layout/src/Root.tsx
packages/layout/src/layout-common-slots/CommonSlots.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/529)

Feat: Add Switchers & Profile common slots

---

build/api/admin.api.md
packages/admin-sandbox/admin/pages/inputs.tsx
packages/admin/src/components/bindingFacade/fields/useFieldControl.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/526)

fix(admin): Use onBlur & onFocus events on Field

---

packages/ui/src/index.css
packages/ui/src/styles/tailwind-support.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/532)

feat(ui): Add Tailwind support

---

packages/utilities/src/dom/dataAttribute.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/534)

fix(utilities): Support `undefined` & `null` in `dataAttribute()`

---

build/api/admin.api.md
packages/admin/src/routing/binding/NavigateBackLink.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/539)

feat(admin): Allow control of visually hidden back link label

---

packages/admin/src/components/Dev/IdentityPanel.tsx
packages/ui/src/components/DevBar/index.css
packages/ui/src/components/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/540)

Devpanel: login with email

---

build/api/admin.api.md
packages/admin/src/components/Login/LoginEntrypoint.tsx
packages/admin/src/tenant/components/idp/common.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/543)

feat(admin): allow to hide button of IdP

---

ee/admin-server/src/dic.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/544)

fix(admin-server): use undefined if S3 endpoint is empty string

---

ee/admin-server/src/config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/546)

fix(admin-server): addd "hidden" field in idp provider to config schema

---

packages/ui/src/components/ContainerSpinner/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/542)

fix(ui): ContainerSpinner flash

---

build/api/admin.api.md
packages/admin/src/tenant/components/person/UsersList.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/548)

fix(admin): user list props type fix

---

packages/admin/src/tenant/components/pages/UserListPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/569)

fix(admin): fix default link in user list page

---

packages/admin/src/tenant/components/idp/useIDPAutoInit.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/568)

fix(admin): idp init in backlink param

---

build/api/admin.api.md
packages/admin/src/components/Login/LoginEntrypoint.tsx
packages/admin/src/tenant/components/idp/useIDPAutoInit.ts
packages/admin/src/tenant/components/idp/useInitIDPRedirect.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/571)

feat(admin): show spinner overlay when initiating idp login

---

packages/layout/src/index.css
packages/ui/src/components/DevBar/DevBar.tsx
packages/ui/src/components/DevBar/index.css
packages/ui/src/components/Table/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/574)

fix: Finish container overflow padding

---

packages/layout/src/primitives/Panel.css
packages/layout/src/primitives/PanelBody.css
packages/ui/src/components/Forms/Select/useCommonReactSelectStyles.ts
packages/ui/src/styles/globals.css
packages/ui/src/styles/schemes.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/575)

Improve input borders & over scroll behavior

---

packages/ui/src/components/Forms/Radio/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/586)

fix(ui): Radio buttons labels

---

packages/ui/src/components/Forms/Button/Button.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/589)

fix(ui): Amend removing of insets in buttons list

---

packages/binding/src/core/ErrorsPreprocessor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/595)

ErrorPreprocessor fix

---

packages/layout/src/slots/Provider.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/600)

fix(layout): Remove console logs from Slots Provider

---

packages/admin-sandbox/admin/components/FocalPoint.css
packages/admin-sandbox/admin/components/FocalPoint.tsx
packages/admin-sandbox/admin/pages/index.tsx
packages/admin-sandbox/api/migrations/2023-08-21-152956-focal-point.json
packages/admin-sandbox/api/model/Files.ts
packages/admin/src/components/bindingFacade/upload/internalComponents/SingleFilePreview/SingleFilePreview.tsx
packages/ui/src/components/ActionableBox/index.css
packages/ui/src/components/Box/index.css
packages/ui/src/components/Dialog/Dialog.css
packages/ui/src/components/Dialog/DialogModal.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/597)

sandbox: focal point component

---

packages/ui/src/components/Forms/Button/Button.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/603)

fix(ui): Handle defaults for `Button.type` prop

---

build/api/ui.api.md
packages/ui/src/components/Box/Box.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/607)

feat(ui): Inherit `grow` and `shrink` on `Box`

---

packages/ui/src/deprecated/Layout/LayoutPageContent.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/608)

fix(ui): Table container inset in legacy page content

---

packages/ui/src/components/Editor/EditorToolbar.css

Closes https://github.com/contember/private-issues/issues/111
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/616)

fix(ui): Remove editor toolbar shadow

---

packages/.template/package.json
packages/admin-i18n/package.json
packages/admin/package.json
packages/binding/package.json
packages/brand/package.json
packages/client/package.json
packages/interface-tester/package.json
packages/layout/package.json
packages/react-client/package.json
packages/react-multipass-rendering/package.json
packages/react-utils/package.json
packages/ui/package.json
packages/utilities/package.json
packages/vimeo-file-uploader/package.json
packages/vite-plugin/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/619)

add "types" to conditional exports in package.json

---

packages/ui/src/components/Editor/EditorParagraph.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/626)

fix(ui): Safari render bug

---

packages/ui/src/components/Menu/MenuItem.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/633)

fix(ui): fix expandedByDefault in MenuItem

---

build/api/react-client.api.md
packages/react-client/src/components/RichTextRenderer/RichTextBlock.ts
packages/react-client/src/components/RichTextRenderer/RichTextRenderer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/630)

Allow richtext renderer readonly props

---

packages/ui/src/components/Forms/Inputs/FloatInput.tsx
packages/ui/src/components/Forms/Inputs/NumberInput.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/635)

fix(ui): allow negative numbers in number input

---

packages/react-utils/src/hooks/useOnElementResize.ts

it was causing `ResizeObserver loop completed with undelivered notifications` error in some cases
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/641)

fix useOnElementResize

---

build/api/binding.api.md
packages/binding/src/queryLanguage/CacheStore.ts
packages/binding/src/queryLanguage/Parser.ts
packages/binding/src/queryLanguage/tokenList.ts
packages/binding/tests/cases/unit/queryLanguage/filter.spec.tsx
packages/binding/tests/cases/unit/queryLanguage/general.spec.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/643)

query language quantifiers

---

packages/react-datagrid-ui/src/rendering/DataGridContainer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/645)

fix(react-datagrid-ui): pass correct env

---

build/api-extractor.json
build/api/client-content.api.md
packages/binding/src/core/DataBinding.ts
packages/client-content-generator/src/generate.ts
packages/client-content/src/ContentClient.ts
packages/client-content/tests/cases/unit/lib.ts
packages/client-content/tests/cases/unit/mutation.test.ts
packages/client-content/tests/cases/unit/query.test.ts
packages/client/tests/cases/unit/generateUploadUrlMutationBuilder.spec.ts
packages/graphql-builder/src/GraphQlQueryPrinter.ts
packages/graphql-builder/tests/cases/unit/builder.test.ts
packages/react-datagrid/src/internal/useDataGridTotalCount.ts

- allow to generate the client from stdin
- pass graphql client instead of execute function
- variable deduplication

content client minor improvements

---

packages/vite-plugin/src/index.ts

- make options optional
- return whole HTML in handler with contember-build-version tag

Update Contember Vite plugin

---

build/api/client-content.api.md
packages/client-content/src/nodes/TypedEntitySelection.ts
packages/client-content/tests/cases/unit/types.test.ts

This fixes issues with arg suggestion on incomplete code.

Content client types refactoring

---

build/api/react-binding.api.md
packages/react-binding/src/helperComponents/If.tsx

Alternative to context approach in #696.

feat(react-binding): add "then" and "else" props to If component

---

packages/playground/admin/app/components/navigation.tsx
packages/playground/admin/app/pages/custom.tsx
packages/playground/admin/app/pages/grid.tsx
packages/playground/api/migrations/2024-06-10-144526-grid-article-view.json
packages/playground/api/model/Grid.ts

- custom component to show how to use `useField`
- entity view

Add more examples to playground
