contember/interface

packages/admin/src/styles/parts/navbar.sass
packages/admin/src/styles/parts/sideDimensions.sass
packages/ui/src/components/Containers/Section/section.sass
packages/ui/src/components/Layout/LayoutChrome.sass
packages/ui/src/components/Layout/LayoutPage.sass
packages/ui/src/components/SectionTabs/SectionTabs.sass
packages/ui/src/styles/_variables.scss
packages/ui/src/styles/components/titleBar.sass

Closes #79
Custom properties are not possible to be used in `@media`

Fix breakpoints

---

packages/ui/src/components/Box/Box.sass
packages/ui/src/components/Box/Box.tsx
packages/ui/src/components/Table/Table.tsx

To add labels outside of the box `FieldContainer` is being used.  Problem is caused by the use of `<label>` HTML component, which should only be used with focusable inputs.
Also fixes no-padding regression styles and introduces interface prop to pair with class styles.
Closes https://github.com/contember/private-issues/issues/12

Fix table popups

---

packages/admin/src/components/pageRouting/Pages.tsx

Because component name in React should aways start with uppercase letter, we need to normalize it back to lowercase when using it as page name.
~~~tsx
export const index = (
<GenericPage pageName="index">
Welcome to Contember Admin!
</GenericPage>
)
~~~
~~~tsx
export const Index = () => (
<GenericPage pageName="index">
Welcome to Contember Admin!
</GenericPage>
)
~~~

Pages: lower case first letter of page named based on export

---

packages/ui/src/styles/components/input.sass

_Screenshot in Safari Version 15.2 (17612.3.6.1.6):_
Closes https://github.com/contember/private-issues/issues/49

Fix vertical aligment of date time inputs

---

packages/ui/src/styles/components/menu.sass

Fix missing focus when navigating without keyboard

Fix missing pseudo selector

---

packages/admin/src/components/Login/LoginEntrypoint.tsx
packages/admin/src/components/MiscPageLayout.tsx
packages/admin/src/styles/_globalOverrides.sass
packages/admin/src/tenant/components/password/CreateResetPasswordRequestForm.tsx
packages/admin/src/tenant/components/password/FillResetPasswordTokenForm.tsx
packages/admin/src/tenant/components/person/Login.tsx
packages/ui/src/components/Box/Box.tsx
packages/ui/src/components/Forms/Button/Button.sass
packages/ui/src/components/Message/Message.sass

Fixed layout:
Closes https://github.com/contember/private-issues/issues/52

Fix global layout style & Update login layout

---

packages/admin/src/styles/_globalOverrides.sass
packages/admin/src/styles/_variables.sass
packages/ui/src/styles/_customProperties.sass
packages/ui/src/styles/_root.sass
packages/ui/src/styles/index.sass

Note: Only used font weights are being downloaded, see Font loading section of https://web.dev/font-best-practices/
Closes #

Include `@font-face` declarations by default

---

packages/admin/src/components/bindingFacade/richText/blockEditor/BlockEditor.tsx

`<label>` has special _powers_ (focusing input within its children) but when used on the content editor renders it unusable. FieldContainer around the content editor uses such `<label>` by default and needs to be disabled for this special use-case.

Hotfix: BlockEditor.tsx

---

packages/admin/src/components/bindingFacade/collections/DataGrid/base/DataGridContainer.tsx
packages/admin/src/components/bindingFacade/collections/helpers/EmptyMessage.tsx
packages/ui/src/components/Box/Box.sass

- Fixes display of message components (defaultly meant to be used outside of the table cess)
- Seamless should not remove `Box` padding, there's an explicit padding prop for that (fix)
Closes #

Fix display of `EmptyMessage` component

---

packages/admin/src/components/bindingFacade/fields/SlugField.tsx

Fix empty slug leaving `hasUnpersistedChanges()` set to true

---

packages/admin/src/components/bindingFacade/fields/RadioField.tsx

RadioOption interface is defined [here](https://github.com/contember/admin/blob/8f15227c8cbe80ed5eaf7367fdc74048829fb9db/packages/ui/src/components/forms/RadioGroup/types.ts#L3), `disabled` attribure is not present:
```ts
export interface RadioOption {
label: ReactNode
labelDescription?: ReactNode
value: string
}
```

Remove `disabled: false` radio option attribute

---

packages/admin-i18n/package.json
packages/admin/package.json

This pull request adds link to GitHub repository so registries like [npmjs](https://www.npmjs.com/package/@contember/admin) can link to it.

Package: add link to GitHub repository

---

packages/ui/src/components/Forms/Button/Button.sass

Issue: `none` disables other box-shadow rules

Button: Fix focus ring

---

packages/admin/src/components/bindingFacade/buttons/PersistButton.tsx
packages/admin/src/components/bindingFacade/collections/helpers/DeleteEntityButton.tsx
packages/admin/src/tenant/components/person/Login.tsx
packages/ui/src/components/Forms/Button/Button.sass
packages/ui/src/components/Layout/LayoutChrome.sass
packages/ui/src/components/Menu/Menu.sass
packages/ui/src/components/SaveButton.tsx
packages/ui/src/components/Typography/Label.sass
packages/ui/src/styles/_themeSchemes.css
packages/ui/src/types/ButtonDistinction.ts
packages/ui/stories/src/Button.stories.tsx

Adds primary button distinction & removes hacks; desaturates menu
**Changes:**
- Dark theme contrasts
- Light theme colours
- Primary buttons distinction
- Only active, hovered & focus items use control colours
Closes https://github.com/contember/private-issues/issues/84

Improve theming

---

packages/admin/src/components/bindingFacade/collections/helpers/DeleteEntityButton.tsx
packages/ui/src/utils/toThemeClass.ts

Add missing option to apply pseudo state only theme with `:hover` or `:active` (or any other available in the future) suffixes.

Theme class pseudo states

---

packages/admin/package.json
packages/admin/src/components/bindingFacade/richText/blockEditor/editor/overrideInsertBreak.ts
pnpm-lock.yaml

- Editor: Allow node break inside reference ContentOutlet
- Upgrade slate
Closes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/207)

Editor: Allow block splitting in references

---

packages/ui/src/components/RepeaterItemContainer/RepeaterItemContainer.sass

Fixes repeater item hiding behind the repeater while dragging
Does not affect z-index fixes of 845253721ba206a5d7a9b7f7431fabdc00a1593e
Removing `z-index: 2` was too much. Changing to `z-index: 1` still works as expected in both scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/284)

Revert z-index

---

packages/ui/src/components/Menu/Menu.sass

Unifies menu item colours following the fix of the default button intent PR #272 
https://user-images.githubusercontent.com/387611/164646911-d1730733-b75c-447c-a5d7-08cd72ad1603.mov
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/285)

Unify menu item in the light and dark scheme

---

packages/ui/src/styles/components/collapsible.sass

Fixes cases where the expanded collapsible child of another collapsed collapsible parent is clickable and invisible and interferes with other menu items.
Closes #275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/288)

FIx nested callapsible overflow issue

---

packages/admin-sandbox/admin/components/ContentField.tsx
packages/admin-sandbox/admin/components/Navigation.tsx
packages/admin-sandbox/admin/pages/locales.tsx
packages/admin-sandbox/admin/pages/tags.tsx
packages/admin-sandbox/api/migrations/2022-05-05-112442-locale-label.json
packages/admin-sandbox/api/migrations/2022-05-05-145615-locales-order.json
packages/admin-sandbox/api/model/Article.ts
packages/admin-sandbox/api/model/Locale.ts
packages/ui/src/components/ActionableBox/ActionableBox.sass
packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass
packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx
packages/ui/src/components/Forms/FieldSet/FieldSet.sass
packages/ui/src/styles/components/editorBlockBoundary.sass

**Fix consists of `ActionableBox` selectors split:**
- Removes unnecessary stacking context caused by `transform`
- Removes `z-index` override within Editor Block
How to confirm functionality:
1. Navigate to **Homepage**
2. Add at least 2 image blocks
3. Click select of the Align field in the first block
4. Confirm position of the option is above the second block
Closes: #304 
---
_Other updates and fixes_
**Sandbox:**
- Improve model of `Locale` and `TagLocale`
- Add Locales page
- Make `TagLocale` sorbable (Tags page)
- Show align radio buttons field also as select in `FieldContainer` (for testing)
**Extra fixes:**
- `FieldContainer`: Hide errors if array is empty
- Handle wrapped elements in `FieldContainer` & `FieldSet` with `contenteditable="false"` as those should not create extra …

Fix repeater stacking context

---

packages/admin/src/components/bindingFacade/buttons/PersistButton.tsx
packages/ui/src/components/SaveButton.tsx

- Also removes from `PersistButton`
Possible breaking change in foreign code.
Closes: https://github.com/contember/private-issues/issues/102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/323)

Remove `flow="block"` in the `SaveButton`

---

packages/admin/src/tenant/components/member/EditMembership.tsx
packages/ui/src/components/Forms/Select/Select.sass
packages/ui/src/styles/abstract/controlVariants.sass

Fixes:
1. seamless select having transparent background set, now omitted for focus & hover pseudo states.
2. removes extra min-height taking border-width into account on select element type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/328)

Fix seamless select

---

packages/ui/src/components/Forms/FieldContainer/FieldContainer.sass
packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx

- Add backward compatible optional `layout` prop
- Extend `HTMLDivElement`
Closes: https://github.com/contember/private-issues/issues/103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/325)

FieldContainer: Opt-out from one-column forms layout

---

packages/ui/src/components/Collapsible/Collapsible.sass
packages/ui/src/components/Collapsible/Collapsible.tsx
packages/ui/src/components/Collapsible/index.sass
packages/ui/src/components/Collapsible/index.ts
packages/ui/src/components/index.sass
packages/ui/src/styles/components/index.sass

Fixes regression of the collapsible overflows outside of the menu
while keeps nested collapsibles working in the menu.
Closes: https://github.com/contember/private-issues/issues/113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/338)

Collapsible: Change application of the oferflows

---

packages/ui/src/components/RepeaterItemContainer/RepeaterItemContainer.sass

Fixes hidden boxes while dragging on small screens
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/378)

Fix `RepeaterItemContainer`: Bump `z-index` for small screens

---

build/api/binding.api.md
packages/admin/src/components/bindingFacade/environment/DimensionsSwitcher/DimensionsSwitcher.tsx
packages/binding/src/accessorTree/AccessorTree.tsx
packages/binding/src/accessorTree/AccessorTreeState.ts
packages/binding/src/accessorTree/AccessorTreeStateAction.ts
packages/binding/src/accessorTree/AccessorTreeStateOptions.ts
packages/binding/src/accessorTree/accessorTreeStateReducer.ts
packages/binding/src/accessorTree/useDataBinding.ts
packages/binding/src/accessors/BindingConfig.ts
packages/binding/src/core/Config.ts
packages/binding/src/core/DataBinding.ts
packages/binding/src/core/TreeStore.ts
packages/binding/src/core/schema/SchemaLoader.ts
packages/binding/src/coreComponents/DataBindingProvider.tsx
packages/binding/tests/cases/unit/core/bindingFactory.ts

- always refresh databinding on env change, but keep tree store
- remove refreshOnEnvironmentChange
- refresh tree store only on persist
- always pass environment with schema to databinding
- make env with schema available to all provider children
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/400)

databinding provider improvements

---

packages/ui/src/components/Forms/Inputs/SlugInput.sass
packages/ui/src/styles/components/editorCanvas.sass

- editor canvas padding
- slug input minus border width
Closes: https://github.com/orgs/contember/projects/11/views/17
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/416)

Fix vertical input sizes

---

packages/ui/src/components/Aether/Aether.sass
packages/ui/src/styles/components/containerSpinner.sass

- Slow queries will transition to dimmed background to further amplify the UI is not ready to be used while spinner is active
Closes: https://github.com/contember/private-issues/issues/129
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/admin/410)

Use transparent background for `SpinnerContainer` in most cases

---

build/api/binding.api.md
build/api/react-client.api.md
build/api/react-utils.api.md
build/api/ui.api.md
package.json
packages/admin-i18n/src/ambient.d.ts
packages/admin/src/ambient.d.ts
packages/admin/src/components/bindingFacade/richText/editorSelection/useToolbarsState.ts
packages/binding/src/ambient.d.ts
packages/react-client/src/ambient.d.ts
packages/react-utils/src/ambient.d.ts
packages/react-utils/src/hooks/useDebounceCallback.ts
packages/ui/src/ambient.d.ts
packages/vite-plugin/src/tsconfig.json
scripts/lint/module-import-linter.ts
tsconfig.settings.json
yarn.lock

This adds type for `import.meta` to every package extending from base `tsconfig.json` and removes necessity to define types on per-package basis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/488)

Add types from `vite/client` to support `import.meta.env.DEV`

---

packages/ui/src/components/Divider/index.css

This fixes divider margins depending on stack orientation with new data attributes.
- This also render divider as zero width/height element so it doesn’t affect layout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/602)

fix(ui): Divider orientation margins

---

packages/ui/src/styles/globals.css

This PR adds scales for icons that were meant to be present in 1.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/623)

fix(ui): Add forgotten icons scale CSS when <= 1

---

package.json
packages/utilities/src/deprecate/deprecate.ts
packages/utilities/tests/deprecate/deprecate.test.ts
packages/utilities/tests/deprecate/fallback.test.ts
packages/utilities/tests/types/Primitive.test.ts
packages/utilities/tests/types/RequiredDeepPlainObject.test.ts
yarn.lock

This PR adds tests for deprecate utilities and replaces typescript test utility with one already included in `vitest` package with same API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/621)

refactor(utilities): Add tests to deprecate utilities

---

packages/ui/src/components/Editor/EditorCanvas.css

This PR fixes regression where the bottom padding reserving space for hovering toolbar is overridden by the CSS rules that follow later.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/634)

fix(ui): Reorder CSS

---

packages/admin/src/components/bindingFacade/environment/DimensionsSwitcher/DimensionsRenderer.tsx

This PR fixes visuals of Dimensions switcher with `maxItems` set > 1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/636)

fix(admin): Display of max items in dimensions switcher

---

packages/ui/src/components/Forms/FieldContainer/FieldContainer.tsx

This PR resolves unintended setting of min height on `FieldContainer` label sub-container in cases where it is not required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/637)

fix(ui): Restrict setting style to positions on left and right

---

packages/react-datagrid/src/grid/createDataGrid.tsx
packages/react-datagrid/src/internal/gridTemplateAnalyzer.ts
packages/react-datagrid/src/internal/useDataGridState.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/646)

fix(react-datagrid): pass env as a static context when analyzing cells

---

build/api/layout.api.md
packages/layout/src/slots/contexts.ts
packages/layout/src/slots/types.ts

This PR improves typings of the return type for `useSlotTargetsFactory()` and also upgrades current Typescript version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/interface/639)

fix(layout): Update return type of `useSlotTargetsFactory()`

---

packages/playground/admin/lib/components/layout.tsx

This PR improves how the Layout handles scrollbar appearance.
Whenever scrollbar-y appears, the Layout's width will change accordingly, ensuring that the content doesn't visually "jump"

feat(playground): better `Layout` overflow styling
